name: Test and Build
on:
  push:
    branches-ignore:
      - main
jobs:
  # bump:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: |
  #         git config --global user.name "$GITHUB_ACTOR"
  #         git config --global user.email "$GITHUB_ACTOR@github.com"
  #         npm version patch
  #         VERSION=$(node -p "require('./package.json').version")
  #         BRANCH="release/$VERSION"
  #         echo "Checking out $BRANCH"
  #         git checkout -b "$BRANCH"
  #         git push --set-upstream origin "$BRANCH"
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: echo "PACKAGE_VERSION=$VERSION >> $GITHUB_ENV"
      - run: cat $GITHUB_ENV
  print_version:
    needs: [version]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: env
      - run: echo "Package version is $PACKAGE_VERSION"
  # build:
  #   # needs: [bump]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v3 
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'
  #     - run: npm ci
  #     - run: npm run build