name: Test and Build
on:
  push:
    branches-ignore:
      - main
jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          npm version patch
          VERSION=$(node -p "require('./package.json').version")
          BRANCH="release/$VERSION"
          echo "Checking out $BRANCH"
          echo git checkout -b "$BRANCH"
          echo git push --set-upstream origin "$BRANCH"
  set-version:
    needs: [bump]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: get_version
        uses: actions/checkout@v3
      - run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "MICAH VERSION IS $VERSION"
          echo "package_version=$VERSION" >> "$GITHUB_OUTPUT"
    # outputs:
    #   package_version: ${{ steps.get_version.outputs.package_version }}
  # print_version:
  #   needs: [version]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - env:
  #         pkg_ver: ${{ needs.set-version.outputs.version}}
  #       run: echo "Package version is $pkg_ver"
  # build:
  #   # needs: [bump]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v3 
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'
  #     - run: npm ci
  #     - run: npm run build